<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="1" failures="1" errors="0" time="8.085">
  <testsuite name="Example" errors="0" failures="1" skipped="0" timestamp="2021-08-03T17:59:57" time="7.673" tests="1">
    <testcase classname="Example should have description text on welcome screen" name="Example should have description text on welcome screen" time="0.001">
      <failure>DetoxRuntimeError: Failed to run application on the device

HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for &quot;ready&quot; message (over WebSocket) from the instrumentation process.
    at call (/Users/jeevankishore/not-work/rnDetox/e2e/setup.js:6:16)
    at tryCatch (/Users/jeevankishore/not-work/rnDetox/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator._invoke (/Users/jeevankishore/not-work/rnDetox/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.call (/Users/jeevankishore/not-work/rnDetox/node_modules/regenerator-runtime/runtime.js:119:21)
    at tryCatch (/Users/jeevankishore/not-work/rnDetox/node_modules/regenerator-runtime/runtime.js:63:40)
    at invoke (/Users/jeevankishore/not-work/rnDetox/node_modules/regenerator-runtime/runtime.js:155:20)
    at /Users/jeevankishore/not-work/rnDetox/node_modules/regenerator-runtime/runtime.js:190:11
    at new Promise (&lt;anonymous&gt;)
    at callInvokeWithMethodAndArg (/Users/jeevankishore/not-work/rnDetox/node_modules/regenerator-runtime/runtime.js:189:16)
    at AsyncIterator._invoke (/Users/jeevankishore/not-work/rnDetox/node_modules/regenerator-runtime/runtime.js:212:13)
    at AsyncIterator.next (/Users/jeevankishore/not-work/rnDetox/node_modules/regenerator-runtime/runtime.js:119:21)
    at Object.exports.async (/Users/jeevankishore/not-work/rnDetox/node_modules/regenerator-runtime/runtime.js:239:14)
    at _callee (/Users/jeevankishore/not-work/rnDetox/e2e/setup.js:5:11)
    at Promise.then.completed (/Users/jeevankishore/not-work/rnDetox/node_modules/jest-circus/build/utils.js:390:28)</failure>
    </testcase>
  </testsuite>
</testsuites>